### ISSUE TITLE
Crashes the Extension Host of VS Code

### ISSUE THREAD

**Issue by COD3BREAK3R** [xanhtool/snap-style-vscode#2]
### Download this extension for VS Code and Chrome and when installing and then restarting VS Code causes the extension host to stop working, this is the message I could see from the VS Code development tools:

C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.5\dist\extension.js:361

!function(f,s){"use strict";a=[],void 0===(o="function"==typeof(t=function(){!function(){var e=void 0!==n;if(e)return n;if("undefined"==typeof document||!document.getElementsByTagName)return null;var i,r=document.currentScript||(i=document.getElementsByTagName("script"))[i.length-1],t=r&&r.src;t&&("/sass.js"===t.slice(-8)?t.slice(0,-8):"/sass.sync.js"===t.slice(-13)&&t.slice(0,-13))}();var i,t=void 0!==t?t:{},a={};for(i in t)t.hasOwnProperty(i)&&(a[i]=t[i]);t.arguments=[],t.thisProgram="./this.program",t.quit=function(e,i){throw i},t.preRun=[],t.postRun=[];var o=!1,f=!1,s=!1,l=!1;o="object"==typeof window,f="function"==typeof importScripts,s="object"==typeof process&&!o&&!f,l=!o&&!s&&!f;var c="";function u(e){return t.locateFile?t.locateFile(e,c):c+e}if(s){var A,d;c=n+"/",t.read=function(e,i){var n;return(n=ur(e))||(A||(A=r(19)),d||(d=r(20)),e=d.normalize(e),n=A.readFileSync(e)),i?n:n.toString()},t.readBinary=function(e){v

abort({}). Build with -s ASSERTIONS=1 for more info.

---------------------------------------------------------

**I am using:**

- VS Code 1.36.1
- Windows 10 1903 x64

**Comment by hiepxanh** [comment]
can you take the screen shoot? that will help me better to fix that bug

**Comment by COD3BREAK3R** [comment]
Sure, sorry for the delay, look at this
![Captura de pantalla (42)](https://user-images.githubusercontent.com/51484063/62655679-81dfb000-b930-11e9-94a6-9105d27543a1.png)
![Captura de pantalla (43)](https://user-images.githubusercontent.com/51484063/62655680-82784680-b930-11e9-87d4-acc5026bf901.png)

**Comment by COD3BREAK3R** [comment]
> 
> 
> can you take the screen shoot? that will help me better to fix that bug

Look at the screenshots above.

**Comment by hiepxanh** [comment]
@COD3BREAK3R thank you bro, I will take a look

**Comment by hiepxanh** [comment]
it seem like there is many report on the recently vscode update, for example [#112](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/112) [#197](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/197)  [#53](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/53)
[#112](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/112)
[#193](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/193)

I counter this problem between my plugin and `setting sync` plugin. At your side, the problem may be the conflict between this plugin and `color-hightlight` plugin or `setting-sync` plugin.
I already try other solution like node-sass but it just not work. 

Right know you only can install this VSCode Insider which already fix the conflict at here [VSCode Insiders](https://code.visualstudio.com/docs/?dv=win&build=insiders). Then we only can wait until they fix that in the next VSCode new version is release. I will let this issue open.
@COD3BREAK3R

**Comment by COD3BREAK3R** [comment]
> it seem like there is many report on the recently vscode update, for example [#112](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/112) [#197](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/197) [#53](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/53)
> [#112](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/112)
> [#193](https://github.com/ritwickdey/vscode-live-sass-compiler/issues/193)
> 
> I counter this problem between my plugin and `setting sync` plugin. At your side, the problem may be the conflict between this plugin and `color-hightlight` plugin or `setting-sync` plugin.
> I already try other solution like node-sass but it just not work.
> 
> Right know you only can install this VSCode Insider which already fix the conflict at here [VSCode Insiders](https://code.visualstudio.com/docs/?dv=win&build=insiders). Then we only can wait until they fix that in the next VSCode new version is release. I will let this issue open.
> @COD3BREAK3R

ok, we just have to wait for the problem to be solved

**Comment by hiepxanh** [comment]
@COD3BREAK3R  hi, I can see that [ VSCode 1.37](https://code.visualstudio.com/updates/v1_37) just release today. And it already fix extension conflict with other. Don't you mind if you upgrade your VSCode to the newest version [ VSCode 1.37](https://code.visualstudio.com/updates/v1_37) and then try to install my extension again?
Please install it with this [chrome extension](https://chrome.google.com/webstore/detail/snap-style/banpiopiepkejkfomncchpdokpnaejnh) and add necessary port in the chrome extension option like this image:
![image](https://user-images.githubusercontent.com/16970990/63031047-92b69580-bedd-11e9-9716-edc6d962e2d3.png)

**Comment by COD3BREAK3R** [comment]
> @COD3BREAK3R hi, I can see that [ VSCode 1.37](https://code.visualstudio.com/updates/v1_37) just release today. And it already fix extension conflict with other. Don't you mind if you upgrade your VSCode to the newest version [ VSCode 1.37](https://code.visualstudio.com/updates/v1_37) and then try to install my extension again?
> Please install it with this [chrome extension](https://chrome.google.com/webstore/detail/snap-style/banpiopiepkejkfomncchpdokpnaejnh) and add necessary port in the chrome extension option like this image:
> ![image](https://user-images.githubusercontent.com/16970990/63031047-92b69580-bedd-11e9-9716-edc6d962e2d3.png)

Ok, I will do the test again and update VS Code, I will notify you when I finish testing.

**Comment by hiepxanh** [comment]
@COD3BREAK3R  sorry, it still not resolve yet, I just suffer the crash again, I will try to fix it again.

**Comment by hiepxanh** [comment]
@COD3BREAK3R  I just upgarde to 0.0.8 version. That won't be conflict anymore. Please try it if you have time.

**Comment by COD3BREAK3R** [comment]
> @COD3BREAK3R I just upgarde to 0.0.8 version. That won't be conflict anymore. Please try it if you have time.

Sure, I already downloaded it, when I have time I try it and tell you if it works.

**Comment by COD3BREAK3R** [comment]
@hiepxanh 

After installing the VS Code extension this time, do not crash the extension host, but it does not work.

I was lifting the server with XAMPP, I opened the Chrome extension and put "localhost" in the configuration and the extension did not refresh the page. I'm loading the unpackaged extension from Chrome's developer options because I don't have internet in my home.

 This is what caught my attention of the VSCode development options:

```
workbench.main.js:242 [Extension Host] error while complie sass CssSyntaxError: <css input>:1:1: Unknown word

> 1 | <!DOCTYPE html>
    | ^
  2 | <html lang="en">
  3 | 

    at e.module.exports.c.error (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:186:16151)
    at e.module.exports.t.unknownWord (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:52668)
    at e.module.exports.t.other (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:48254)
    at e.module.exports.t.parse (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:47239)
    at s (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:98:13409)
    at new e (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:186:29199)
    at e.<anonymous> (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:186:27925)
    at e.t [as process] (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:186:27760)
    at module.exports.t.StyleCompiler.<anonymous> (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:8830)
    at Generator.next (<anonymous>)
    at module.exports.r (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:8545)
    at new Promise (<anonymous>)
    at module.exports.r (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:8322)
    at module.exports.t.StyleCompiler.complie (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:8753)
    at module.exports.t.FileWatcher.<anonymous> (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:7285)
    at Generator.next (<anonymous>)
    at s (C:\Users\MATRIX-PC\.vscode\extensions\hiepxanh.snap-style-0.0.8\dist\extension.js:353:5833)
t.log @ workbench.main.js:242

```

**Comment by hiepxanh** [comment]
thank you, it clearly that my extension is trying to reading `.html` file, which it shouldn't do this. I will try to fix that. By the way, can you upload your test project folder to github? I will try to make it work with your example before roll out new version. 
Thank you :D

**Comment by COD3BREAK3R** [comment]
Hello, so sorry for the late reply, I will be on vacation for a few days, as soon as I get back to work I will try to publish the website where I am testing its extension to GitHub because right now I do not have access to upload files from the proxy where I am, maybe In a moment of my vacation I went through a Wi-Fi and go to the GitHub repository to the web so you can test your incredible extension (in my house I don't have internet).

Thank you for this incredible extension, sorry for the delay.

**Comment by hiepxanh** [comment]
Yes, feel free to to do it. I'm happy to work with you.

**Comment by COD3BREAK3R** [comment]
I have uploaded the code of the web with which I was testing your extension to GitHub in a .zip file, I hope you find it useful.

https://github.com/COD3BREAK3R/COD3BREAK3R/raw/master/webdeprueba.zip

**Comment by hiepxanh** [comment]
Thank you, I will check this out

**Comment by COD3BREAK3R** [comment]
Hello, how are you? Yesterday I returned from vacation, how is the progress of the extension going?

**Comment by hiepxanh** [comment]
Yeah, I'm have some serious problem that cannot pass yet

Vào Th 5, 19 thg 9, 2019 vào lúc 01:46 COD3BREAK3R <
notifications@github.com> đã viết:

**Comment by hiepxanh** [comment]
@COD3BREAK3R  the crash seem not happen anymore on new version of VSCode, can you check this out?

**Comment by COD3BREAK3R** [comment]
> @COD3BREAK3R the crash seem not happen anymore on new version of VSCode, can you check this out?

Sorry for replying too late, I have installed the extension and haven't seen an extension host crash in VSCode
